use strict;
use warnings;
use File::Find;

# tools/gen_vanilla_map.pl <decompiled ZM folder>
# Writes tools/vanilla_namespaces.txt: "helper<TAB>namespace" for every unqualified vanilla SCRIPT function the
# sources call. Engine builtins are left out (they need no namespace). The map lets tools/pack.pl emit a merged
# file whose calls are fully qualified, so the single file needs no #include resolution at load.
my $ref = shift or die "usage: gen_vanilla_map.pl <ZM folder>\n";

my %ours;
for my $f (glob('mg_*.gsc')) {
    open my $h, '<:raw', $f or next;
    while (my $l = <$h>) { $ours{$1} = 1 if $l =~ /^([a-z_][a-z0-9_]*)\s*\(/ }
    close $h;
}

my %called;
my %kw = map { $_ => 1 } qw(if while for switch return foreach thread wait waittill notify endon breakpoint);
for my $f (glob('mg_*.gsc')) {
    open my $h, '<:raw', $f or next;
    local $/;
    my $s = <$h>;
    close $h;
    $s =~ s{//[^\n]*}{}g;
    while ($s =~ /(?<![\w:\x5c])([a-z_][a-z0-9_]*)\s*\(/g) {
        my $n = $1;
        next if $kw{$n} || $ours{$n};
        $called{$n} = 1;
    }
}

# where does each name come from in the vanilla scripts?
my %def;
my @files;
find( sub { push @files, $File::Find::name if /\.gsc$/i }, $ref );
for my $f (@files) {
    open my $h, '<:raw', $f or next;
    my $ns = $f;
    $ns =~ s{^.*?/ZM/}{};
    $ns =~ s{^[^/]+/}{};          # drop the per-map folder (Core/, Maps/Tranzit/, ...)
    $ns =~ s{\.gsc$}{};
    while (my $l = <$h>) {
        next unless $l =~ /^([a-z_][a-z0-9_]*)\s*\(/;
        my $n = $1;
        next unless $called{$n};
        push @{ $def{$n} }, $ns;
    }
    close $h;
}

# prefer the three utility scripts our files include, then anything else
my @prefer = ( 'maps/mp/zombies/_zm_utility', 'maps/mp/_utility', 'common_scripts/utility' );
open my $o, '>', 'tools/vanilla_namespaces.txt' or die;
print $o "# helper<TAB>namespace - unqualified vanilla script functions called by the sources (generated by\n";
print $o "# tools/gen_vanilla_map.pl). Engine builtins are absent on purpose: they resolve without a namespace.\n";
my ($mapped, $builtin) = (0, 0);
for my $n (sort keys %called) {
    my @ns = $def{$n} ? do { my %u; grep { !$u{$_}++ } @{ $def{$n} } } : ();
    if (!@ns) { $builtin++; next }
    my $pick = $ns[0];
    for my $p (@prefer) { if (grep { $_ eq $p } @ns) { $pick = $p; last } }
    printf $o "%s\t%s\n", $n, $pick;
    $mapped++;
}
close $o;
print "$mapped vanilla helpers mapped, $builtin treated as engine builtins\n";
